import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

/*
 * The CMS schema. Four concerns, deliberately separate tables:
 *
 *   admin_users + sessions   who may write
 *   posts + images           what gets published
 *   audit_log                what happened, and who did it
 *
 * Sessions are rows rather than stateless tokens so that logging out, locking
 * an account, or revoking a leaked cookie are real operations instead of a wait
 * for expiry. At this scale the extra lookup per request costs nothing.
 */

export const adminUsers = pgTable("admin_users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: varchar("email", { length: 320 }).notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  name: varchar("name", { length: 120 }).notNull(),
  isActive: boolean("is_active").notNull().default(true),
  lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const sessions = pgTable(
  "sessions",
  {
    // The primary key IS the cookie value, so it is generated by the database's
    // CSPRNG and never derived from anything user-supplied.
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => adminUsers.id, { onDelete: "cascade" }),
    /*
     * Synchronizer CSRF token, handed to the client in the login response and
     * required as a header on every state-changing request.
     *
     * A double-submit cookie cannot work here: the admin UI is served from
     * assistsec.nl and this API from cms.assistsec.nl, so its JavaScript cannot
     * read a cookie this origin sets. And SameSite=Lax is not a defence either
     * — those two hosts are the *same site*, so any subdomain can send
     * credentialed requests. Binding the token to the session row and never
     * putting it in a cookie is what actually closes that.
     */
    csrfToken: varchar("csrf_token", { length: 64 }).notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    userAgent: varchar("user_agent", { length: 400 }),
    ip: varchar("ip", { length: 64 }),
  },
  (table) => [index("ix_sessions_user").on(table.userId)],
);

export const posts = pgTable(
  "posts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    slug: varchar("slug", { length: 140 }).notNull(),
    // Only "en" is written today. The column exists because adding it to a
    // populated table later, with the unique constraint it implies, is far more
    // painful than carrying it from the start.
    locale: varchar("locale", { length: 5 }).notNull().default("en"),
    title: varchar("title", { length: 200 }).notNull(),
    category: varchar("category", { length: 32 }).notNull(),
    excerpt: text("excerpt").notNull(),
    /** Sanitized on write. Never store what the client sent. */
    body: text("body").notNull(),
    readMinutes: integer("read_minutes").notNull().default(1),
    status: varchar("status", { length: 16 }).notNull().default("draft"),
    isFeatured: boolean("is_featured").notNull().default(false),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    authorId: uuid("author_id").references(() => adminUsers.id, {
      onDelete: "set null",
    }),
    lastEditedById: uuid("last_edited_by_id").references(() => adminUsers.id, {
      onDelete: "set null",
    }),
    seoTitle: varchar("seo_title", { length: 200 }),
    seoDescription: varchar("seo_description", { length: 320 }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("uq_posts_slug_locale").on(table.slug, table.locale),
    index("ix_posts_status_published").on(table.status, table.publishedAt),
    /*
     * The shape of a URL, enforced where it cannot be bypassed.
     *
     * Application code already builds slugs this way, but this table is also
     * reachable from the seed importer and from psql, and a slug that is empty,
     * uppercase, non-ASCII or hyphen-topped is either unreachable through the
     * public lookup or resolves to a different address than the one stored. The
     * unique index above keeps two posts apart; this keeps each one
     * addressable.
     */
    check(
      "ck_posts_slug_shape",
      sql`${table.slug} ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'`,
    ),
  ],
);

/*
 * Every address a post has ever had, apart from its current one.
 *
 * Renaming a published article moves its slug so the URL keeps matching the
 * headline — but the old address is already in inbound links, in someone's
 * bookmarks and in search results, and it has to keep working. Each rename
 * files the outgoing slug here, and a request for one redirects to wherever
 * that post lives now.
 *
 * Unique on (slug, locale) for the same reason `posts` is: an address belongs
 * to one article. The uniqueness check for a new slug consults both tables, so
 * a post can never claim a URL that still points somewhere else.
 */
export const postSlugs = pgTable(
  "post_slugs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    postId: uuid("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),
    slug: varchar("slug", { length: 140 }).notNull(),
    locale: varchar("locale", { length: 5 }).notNull().default("en"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("uq_post_slugs_slug_locale").on(table.slug, table.locale),
    index("ix_post_slugs_post").on(table.postId),
    check(
      "ck_post_slugs_slug_shape",
      sql`${table.slug} ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'`,
    ),
  ],
);

export const images = pgTable(
  "images",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Server-generated. This is the only value that ever reaches the filesystem.
    filename: varchar("filename", { length: 255 }).notNull().unique(),
    originalFilename: varchar("original_filename", { length: 255 }).notNull(),
    contentType: varchar("content_type", { length: 100 }).notNull(),
    sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(),
    width: integer("width"),
    height: integer("height"),
    // Nullable: an image is uploaded before the post it belongs to is saved, and
    // stays orphaned if the author abandons the draft. The column is what makes
    // those orphans findable later.
    postId: uuid("post_id").references(() => posts.id, {
      onDelete: "set null",
    }),
    uploadedById: uuid("uploaded_by_id").references(() => adminUsers.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [index("ix_images_post").on(table.postId)],
);

export const auditLog = pgTable(
  "audit_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    actorId: uuid("actor_id").references(() => adminUsers.id, {
      onDelete: "set null",
    }),
    action: varchar("action", { length: 64 }).notNull(),
    resourceId: varchar("resource_id", { length: 140 }),
    metadata: jsonb("metadata"),
    ip: varchar("ip", { length: 64 }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [index("ix_audit_created").on(table.createdAt)],
);

/*
 * A digital exposure scan.
 *
 * Two shapes share this table because they share a lifecycle — created,
 * progressed through stages, finished or failed, then purged — and differ only
 * in what the subject is and who may read the result. A website scan is public
 * once created: the caller who started it may poll it. An email scan is never
 * readable from the id alone; it is unlocked by a single-use token sent to the
 * address itself (see `scanAccessTokens`).
 *
 * The subject and the findings are stored encrypted rather than in plain
 * columns. A domain is not a secret, but an email address is personal data and
 * the findings attached to it are the most sensitive rows this database will
 * ever hold. One code path that always encrypts is easier to keep right than
 * two that sometimes do, so both kinds go through it.
 *
 * There is deliberately no foreign key to a user: nobody signs in to run a
 * scan, and attaching one identity to another is exactly the correlation this
 * feature must not perform.
 */
export const scans = pgTable(
  "scans",
  {
    /*
     * The public identifier, and the only one that ever reaches a URL. Random
     * rather than sequential so that holding one report never suggests where
     * the next one is.
     */
    id: uuid("id").primaryKey().defaultRandom(),
    kind: varchar("kind", { length: 16 }).notNull(),
    status: varchar("status", { length: 32 }).notNull().default("queued"),
    /** Which locale the requester asked for, so mail matches the site. */
    locale: varchar("locale", { length: 5 }).notNull().default("en"),

    /*
     * AES-256-GCM over the normalized subject. `subjectDigest` is a keyed hash
     * of the same value, which is what makes "have I already scanned this in
     * the last minute" answerable without ever comparing plaintext — and what
     * idempotent creation keys on.
     */
    subjectCipher: text("subject_cipher").notNull(),
    subjectDigest: varchar("subject_digest", { length: 64 }).notNull(),

    /** Encrypted result document. Null until the run finishes. */
    resultCipher: text("result_cipher"),

    /*
     * A coarse band, in the clear, because it is the one field the UI needs
     * before unlocking and the one the CRM is allowed to receive. It carries
     * no detail: "elevated" says nothing about what was found.
     */
    riskBand: varchar("risk_band", { length: 16 }),

    /** Set only once the subject proved control of the address. */
    verifiedAt: timestamp("verified_at", { withTimezone: true }),
    /** Marketing permission, separate from the transactional send. */
    marketingConsent: boolean("marketing_consent").notNull().default(false),

    /** Coarse failure reason for the UI. Never a provider message. */
    failureCode: varchar("failure_code", { length: 32 }),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** When the row stops being readable and becomes eligible for deletion. */
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  },
  (table) => [
    index("ix_scans_digest_created").on(table.subjectDigest, table.createdAt),
    index("ix_scans_expires").on(table.expiresAt),
  ],
);

/*
 * A single-use key to one private report.
 *
 * Only the hash is stored, for the same reason a password is only ever stored
 * hashed: the table is what an attacker reads if they get the database, and a
 * table of live report links is as good as the reports. The plaintext exists
 * once, in the mail that was sent, and nowhere else.
 *
 * `usedAt` is what makes it single-use, and `expiresAt` is what makes an
 * abandoned link stop working on its own.
 */
export const scanAccessTokens = pgTable(
  "scan_access_tokens",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    scanId: uuid("scan_id")
      .notNull()
      .references(() => scans.id, { onDelete: "cascade" }),
    /** SHA-256 of the token that was mailed. Never the token itself. */
    tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(),
    usedAt: timestamp("used_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  },
  (table) => [index("ix_scan_tokens_scan").on(table.scanId)],
);

/*
 * A lead captured when a visitor unlocks a full website report.
 *
 * Stored in the clear, unlike the scan subject: these are details the person
 * volunteered so a salesperson could contact them, so there is every reason to
 * keep them readable and none to encrypt. `scanId` is a plain value rather than
 * a foreign key on purpose — a scan row expires and is deleted, but the lead it
 * produced must outlive it, so the two are not tied together at the database.
 * The email is a company address by the time it lands here; the endpoint
 * refuses free webmail.
 */
export const scanLeads = pgTable(
  "scan_leads",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    scanId: uuid("scan_id").notNull(),
    name: varchar("name", { length: 200 }).notNull(),
    company: varchar("company", { length: 200 }).notNull(),
    position: varchar("position", { length: 200 }).notNull(),
    email: varchar("email", { length: 320 }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [index("ix_scan_leads_created").on(table.createdAt)],
);

/*
 * Contact and demo requests from the marketing site.
 *
 * The row is written before any mail is attempted, and that order is the whole
 * point: delivery depends on a third party that can be down, misconfigured or
 * rate-limiting us, and an inquiry that only ever existed as an SMTP attempt is
 * an inquiry that can be lost silently. Persisting first means the worst case
 * is a mail that has to be resent from a row we still hold, not a customer who
 * wondered why nobody replied.
 *
 * `deliveredAt` records that the mail was accepted by the transport. A row with
 * a null `deliveredAt` is the queue of things somebody still has to look at.
 *
 * Stored in the clear: every field is something the visitor typed into a public
 * form in order to be contacted back, so there is every reason to keep it
 * readable and none to encrypt it.
 */
export const inquiries = pgTable(
  "inquiries",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /** `contact` from /contact, `demo` from /demo. */
    kind: varchar("kind", { length: 20 }).notNull(),
    name: varchar("name", { length: 200 }).notNull(),
    email: varchar("email", { length: 320 }).notNull(),
    company: varchar("company", { length: 200 }),
    /** Job title on a demo request, the chosen service on a contact request. */
    subject: varchar("subject", { length: 200 }),
    phone: varchar("phone", { length: 60 }),
    message: text("message"),
    /** Whether they asked to be emailed about the product. */
    consent: boolean("consent").notNull().default(false),
    /** Which language the form was filled in, so the reply matches. */
    locale: varchar("locale", { length: 10 }).notNull().default("en"),
    deliveredAt: timestamp("delivered_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("ix_inquiries_created").on(table.createdAt),
    // The undelivered queue is the one query that has to stay fast.
    index("ix_inquiries_delivered").on(table.deliveredAt),
    check("ck_inquiries_kind", sql`${table.kind} in ('contact', 'demo')`),
  ],
);

export type AdminUser = typeof adminUsers.$inferSelect;
export type Inquiry = typeof inquiries.$inferSelect;
export type NewInquiry = typeof inquiries.$inferInsert;
export type Scan = typeof scans.$inferSelect;
export type ScanLead = typeof scanLeads.$inferSelect;
export type NewScanLead = typeof scanLeads.$inferInsert;
export type NewScan = typeof scans.$inferInsert;
export type ScanAccessToken = typeof scanAccessTokens.$inferSelect;
export type Post = typeof posts.$inferSelect;
export type PostSlug = typeof postSlugs.$inferSelect;
export type NewPost = typeof posts.$inferInsert;
export type ImageRow = typeof images.$inferSelect;
