import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

/*
 * The CMS schema. Four concerns, deliberately separate tables:
 *
 *   admin_users + sessions   who may write
 *   posts + images           what gets published
 *   audit_log                what happened, and who did it
 *
 * Sessions are rows rather than stateless tokens so that logging out, locking
 * an account, or revoking a leaked cookie are real operations instead of a wait
 * for expiry. At this scale the extra lookup per request costs nothing.
 */

export const adminUsers = pgTable("admin_users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: varchar("email", { length: 320 }).notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  name: varchar("name", { length: 120 }).notNull(),
  isActive: boolean("is_active").notNull().default(true),
  lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const sessions = pgTable(
  "sessions",
  {
    // The primary key IS the cookie value, so it is generated by the database's
    // CSPRNG and never derived from anything user-supplied.
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => adminUsers.id, { onDelete: "cascade" }),
    /*
     * Synchronizer CSRF token, handed to the client in the login response and
     * required as a header on every state-changing request.
     *
     * A double-submit cookie cannot work here: the admin UI is served from
     * assistsec.nl and this API from cms.assistsec.nl, so its JavaScript cannot
     * read a cookie this origin sets. And SameSite=Lax is not a defence either
     * — those two hosts are the *same site*, so any subdomain can send
     * credentialed requests. Binding the token to the session row and never
     * putting it in a cookie is what actually closes that.
     */
    csrfToken: varchar("csrf_token", { length: 64 }).notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    userAgent: varchar("user_agent", { length: 400 }),
    ip: varchar("ip", { length: 64 }),
  },
  (table) => [index("ix_sessions_user").on(table.userId)],
);

export const posts = pgTable(
  "posts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    slug: varchar("slug", { length: 140 }).notNull(),
    // Only "en" is written today. The column exists because adding it to a
    // populated table later, with the unique constraint it implies, is far more
    // painful than carrying it from the start.
    locale: varchar("locale", { length: 5 }).notNull().default("en"),
    title: varchar("title", { length: 200 }).notNull(),
    category: varchar("category", { length: 32 }).notNull(),
    excerpt: text("excerpt").notNull(),
    /** Sanitized on write. Never store what the client sent. */
    body: text("body").notNull(),
    readMinutes: integer("read_minutes").notNull().default(1),
    status: varchar("status", { length: 16 }).notNull().default("draft"),
    isFeatured: boolean("is_featured").notNull().default(false),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    authorId: uuid("author_id").references(() => adminUsers.id, {
      onDelete: "set null",
    }),
    lastEditedById: uuid("last_edited_by_id").references(() => adminUsers.id, {
      onDelete: "set null",
    }),
    seoTitle: varchar("seo_title", { length: 200 }),
    seoDescription: varchar("seo_description", { length: 320 }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("uq_posts_slug_locale").on(table.slug, table.locale),
    index("ix_posts_status_published").on(table.status, table.publishedAt),
    /*
     * The shape of a URL, enforced where it cannot be bypassed.
     *
     * Application code already builds slugs this way, but this table is also
     * reachable from the seed importer and from psql, and a slug that is empty,
     * uppercase, non-ASCII or hyphen-topped is either unreachable through the
     * public lookup or resolves to a different address than the one stored. The
     * unique index above keeps two posts apart; this keeps each one
     * addressable.
     */
    check(
      "ck_posts_slug_shape",
      sql`${table.slug} ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'`,
    ),
  ],
);

/*
 * Every address a post has ever had, apart from its current one.
 *
 * Renaming a published article moves its slug so the URL keeps matching the
 * headline — but the old address is already in inbound links, in someone's
 * bookmarks and in search results, and it has to keep working. Each rename
 * files the outgoing slug here, and a request for one redirects to wherever
 * that post lives now.
 *
 * Unique on (slug, locale) for the same reason `posts` is: an address belongs
 * to one article. The uniqueness check for a new slug consults both tables, so
 * a post can never claim a URL that still points somewhere else.
 */
export const postSlugs = pgTable(
  "post_slugs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    postId: uuid("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),
    slug: varchar("slug", { length: 140 }).notNull(),
    locale: varchar("locale", { length: 5 }).notNull().default("en"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("uq_post_slugs_slug_locale").on(table.slug, table.locale),
    index("ix_post_slugs_post").on(table.postId),
    check(
      "ck_post_slugs_slug_shape",
      sql`${table.slug} ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'`,
    ),
  ],
);

export const images = pgTable(
  "images",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Server-generated. This is the only value that ever reaches the filesystem.
    filename: varchar("filename", { length: 255 }).notNull().unique(),
    originalFilename: varchar("original_filename", { length: 255 }).notNull(),
    contentType: varchar("content_type", { length: 100 }).notNull(),
    sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(),
    width: integer("width"),
    height: integer("height"),
    // Nullable: an image is uploaded before the post it belongs to is saved, and
    // stays orphaned if the author abandons the draft. The column is what makes
    // those orphans findable later.
    postId: uuid("post_id").references(() => posts.id, {
      onDelete: "set null",
    }),
    uploadedById: uuid("uploaded_by_id").references(() => adminUsers.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [index("ix_images_post").on(table.postId)],
);

export const auditLog = pgTable(
  "audit_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    actorId: uuid("actor_id").references(() => adminUsers.id, {
      onDelete: "set null",
    }),
    action: varchar("action", { length: 64 }).notNull(),
    resourceId: varchar("resource_id", { length: 140 }),
    metadata: jsonb("metadata"),
    ip: varchar("ip", { length: 64 }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [index("ix_audit_created").on(table.createdAt)],
);

export type AdminUser = typeof adminUsers.$inferSelect;
export type Post = typeof posts.$inferSelect;
export type PostSlug = typeof postSlugs.$inferSelect;
export type NewPost = typeof posts.$inferInsert;
export type ImageRow = typeof images.$inferSelect;
